services:
  - type: web
    name: MockDotNet-Client
    env: static
    buildCommand: npm run build
    startCommand: npm start
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html